### PR TITLE
skip always dns resolve when ip already exist

### PR DESCRIPTION
**Pull request by fenggui321**

### CODE REVIEW

**Comment by liudf0716** [comment]
although apfree wifidog get its auth_server ip, it cannot promise route will be always online, therefore these dns resolving action was necessary.

**Comment by fenggui321** [comment]
@liudf0716 actually I check this with "if(!is_online() || auth_server->last_ip == NULL){"。but your code check online() line:420. I didn't go through all your code logic, just for hint

**Comment by liudf0716** [comment]
@fenggui321 sorry for my first answer, I didnot read the code carefully.
the logic why everytime auther server's ip was parsed is orginal wifidog's logic, I thank the reason was prepared for such condition:
if user changed auther server, for example ,from a.com to b.com, u don't need to restart wifidog to change its auther server.

**Comment by fenggui321** [comment]
@liudf0716 connect function work with IP, NOT hostname.

**Comment by liudf0716** [comment]
@fenggui321  following your logic, I thought u need modify mark_auth_server_bad function like this:

void
mark_auth_server_bad(t_auth_serv * bad_server)
{
    t_auth_serv *tmp;

    if (bad_server->authserv_fd > 0) {
        close(bad_server->authserv_fd);
        bad_server->authserv_fd = -1;
        bad_server->authserv_fd_ref = 0;
        
       // add those line
      free(bad_server->last_ip);
       bad_server->last_ip = NULL;
    }
    
    if (config.auth_servers == bad_server && bad_server->next != NULL) {
        /* Go to the last */
        for (tmp = config.auth_servers; tmp->next != NULL; tmp = tmp->next) ;
        /* Set bad server as last */
        tmp->next = bad_server;
        /* Remove bad server from start of list */
        config.auth_servers = bad_server->next;
        /* Set the next pointe to NULL in the last element */
        bad_server->next = NULL;
    }

}

**Comment by liudf0716** [comment]
@fenggui321 merged,thanks!
we will check this feature before next release.

**Comment by fenggui321** [comment]
[https://github.com/liudf0716/apfree_wifidog/issues/191](url)  this maybe related with your "mark_auth_server_bad" change.

**Pull request merged**
