### PR TITLE
-m state --state: Replaced by "-m conntrack --ctstate" for compatible…

### PR DESCRIPTION
**Pull request by 809205580**
… newer LEDE

### CODE REVIEW

**Comment by 809205580** [comment]
No problem!

**Comment by liudf0716** [comment]
merged,thanks!

**Comment by liudf0716** [comment]
@809205580 can u add your name to contributor :  
https://github.com/liudf0716/apfree_wifidog/blob/master/contributors.md

**Comment by gigibox** [comment]
`Technically the conntrack match supersedes - and so obsoletes - the state match.`
It is a good idea to apply your policies.

**Pull request merged**
